/**
 * Produces the portable static folder in `out/`.
 *
 * A route handler cannot exist under `output: 'export'`, so app/api is moved
 * aside for the duration of the build and restored afterwards — including if
 * the build throws, which is the whole reason this is a script and not a flag.
 */
import { rename, rm, access, writeFile } from 'node:fs/promises';
import { execSync } from 'node:child_process';

const HTACCESS = `# Generated by scripts/build-static.mjs — do not edit here.

# Serve the exported 404 page instead of Apache's default.
ErrorDocument 404 /404.html

# Compress text. Images are already AVIF/WebP and must not be re-compressed.
<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/css text/plain text/xml
  AddOutputFilterByType DEFLATE application/javascript application/json
  AddOutputFilterByType DEFLATE image/svg+xml
</IfModule>

<IfModule mod_expires.c>
  ExpiresActive On
  # Next.js fingerprints everything under /_next/static, so it can be cached
  # forever — a new build produces new filenames.
  <If "%{REQUEST_URI} =~ m#^/_next/static/#">
    ExpiresDefault "access plus 1 year"
    Header set Cache-Control "public, max-age=31536000, immutable"
  </If>
  # Images are NOT fingerprinted, so a month with revalidation instead.
  ExpiresByType image/avif "access plus 1 month"
  ExpiresByType image/webp "access plus 1 month"
  ExpiresByType image/jpeg "access plus 1 month"
  ExpiresByType image/svg+xml "access plus 1 month"
  ExpiresByType font/woff2 "access plus 1 year"
  # HTML must revalidate or a redeploy never reaches anyone.
  ExpiresByType text/html "access plus 0 seconds"
</IfModule>

<IfModule mod_headers.c>
  Header always set X-Content-Type-Options "nosniff"
  Header always set Referrer-Policy "strict-origin-when-cross-origin"
</IfModule>

# The Open Graph image is exported as a file with NO extension, so Apache
# would serve it as application/octet-stream and every social preview
# (WhatsApp, LinkedIn, Slack, iMessage) would silently fail to render it.
<Files "opengraph-image">
  ForceType image/png
  Header set Cache-Control "public, max-age=2592000"
</Files>

# Correct types in case the host has not registered them.
AddType image/avif .avif
AddType image/webp .webp
AddType font/woff2 .woff2
`;

const API = 'app/api';
const PARKED = '.api-parked';

const exists = async (p) => { try { await access(p); return true; } catch { return false; } };

let parked = false;
try {
  if (await exists(API)) { await rename(API, PARKED); parked = true; }
  await rm('out', { recursive: true, force: true });
  await rm('.next', { recursive: true, force: true });
  execSync('next build', {
    stdio: 'inherit',
    env: { ...process.env, STATIC_EXPORT: '1', NEXT_PUBLIC_STATIC_EXPORT: '1' },
  });
  // Apache config for shared hosting (Hostinger and friends). There is no CDN
  // in front of the files there, so nothing sets cache or compression headers
  // unless this does — and Apache will not serve 404.html for a missing path
  // without being told to.
  await writeFile('out/.htaccess', HTACCESS);

  console.log('\nStatic site written to ./out');
  console.log('Upload the CONTENTS of ./out into public_html (including the hidden .htaccess).');
} finally {
  if (parked) await rename(PARKED, API);
}
