"""
Derives every responsive image variant from the masters in public/ and writes a
manifest the components read.

WHY THIS EXISTS RATHER THAN next/image: this project ships a SECOND build
target (`npm run build:static`) that has to open from disk with no server, so
the Next image optimiser is unavailable by construction. Variants are therefore
generated ahead of time and selected with a plain <picture> element, which
works identically in both targets.

Run: python3 scripts/gen-images.py   (after adding or replacing a master)

Masters are the .jpg files in public/. Everything in public/img/ is generated
and safe to delete.
"""
import base64, io, json, os, shutil
from PIL import Image, ImageFilter

SRC = 'public'
OUT = 'public/img'
WIDTHS = [400, 700, 1000, 1400]
# AVIF ~55 and WebP ~76 sit at about the same perceptual quality as JPEG 78,
# which is where this photography stops showing ringing on the DIN rails.
Q = {'avif': 55, 'webp': 76, 'jpeg': 78}

shutil.rmtree(OUT, ignore_errors=True)
os.makedirs(OUT, exist_ok=True)

manifest, total_src, total_out = {}, 0, 0

for name in sorted(os.listdir(SRC)):
    if not name.endswith('.jpg'):
        continue
    path = os.path.join(SRC, name)
    stem = name[:-4]
    im = Image.open(path).convert('RGB')
    w0, h0 = im.size
    total_src += os.path.getsize(path)

    widths = [w for w in WIDTHS if w <= w0] or [w0]
    if w0 not in widths and w0 < max(WIDTHS):
        widths.append(w0)

    entry = {'w': w0, 'h': h0, 'widths': widths}
    for w in widths:
        h = round(h0 * w / w0)
        r = im.resize((w, h), Image.LANCZOS)
        for fmt, ext in (('avif', 'avif'), ('webp', 'webp'), ('jpeg', 'jpg')):
            f = os.path.join(OUT, f'{stem}-{w}.{ext}')
            r.save(f, fmt.upper() if fmt != 'jpeg' else 'JPEG',
                   quality=Q[fmt], **({'optimize': True, 'progressive': True} if fmt == 'jpeg' else {}))
            total_out += os.path.getsize(f)

    # LQIP: a 20px wide blur, inlined as a data URI. It is the placeholder the
    # frame paints while the real file is in flight, so a photo fades up from
    # its own colours instead of from an empty box.
    tiny = im.resize((20, max(1, round(h0 * 20 / w0))), Image.LANCZOS).filter(ImageFilter.GaussianBlur(1))
    buf = io.BytesIO()
    tiny.save(buf, 'JPEG', quality=40)
    entry['lqip'] = 'data:image/jpeg;base64,' + base64.b64encode(buf.getvalue()).decode()
    manifest[f'/{name}'] = entry

ts = ["/* GENERATED by scripts/gen-images.py — do not edit by hand. */",
      "export type ImageMeta = { w: number; h: number; widths: number[]; lqip: string };",
      "export const images: Record<string, ImageMeta> = " + json.dumps(manifest, indent=2) + ";",
      ""]
open('lib/images.ts', 'w').write('\n'.join(ts))

print(f'masters {total_src/1024:.0f} KB -> variants {total_out/1024:.0f} KB across {len(manifest)} images')
for k, v in manifest.items():
    print(f'  {k:22s} {v["w"]}x{v["h"]}  widths {v["widths"]}  lqip {len(v["lqip"])}B')
